# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(379, 667)
        Form.setStyleSheet("background:qlineargradient(spread:pad, x1:0.621, y1:0.426, x2:0.379, y2:0.733, stop:0.102273 rgba(70, 76, 212, 255), stop:0.844697 rgba(162, 166, 242, 149))")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(70, 358, 251, 41))
        self.lineEdit.setStyleSheet("\n"
"\n"
"\n"
"background: #FFFFFF;\n"
"\n"
"\n"
"border-radius: 20px;\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(132, 419, 137, 51))
        self.pushButton.setStyleSheet("\n"
"background: #484DD5;\n"
"border-radius: 25px;\n"
"font-family: \'Roboto\';\n"
"font-style: normal;\n"
"font-weight: 200;\n"
"font-size: 18px;\n"
"line-height: 21px;\n"
"text-align: center;\n"
"letter-spacing: 0.04em;\n"
"color: #FFFFFF;\n"
"\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(54, 36, 271, 161))
        self.label.setStyleSheet("background-color: transparent;")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/icons/icons/vector.png"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(103, 92, 181, 31))
        self.label_2.setStyleSheet("font-family: \'Roboto\';\n"
"font-style: normal;\n"
"font-weight: 300;\n"
"font-size: 32px;\n"
"line-height: 38px;\n"
"text-align: center;\n"
"letter-spacing: 0.04em;\n"
"\n"
"color: #FFFFFF;\n"
"background-color: transparent;\n"
"text-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(143, 230, 141, 91))
        self.label_3.setStyleSheet("background-color: transparent;")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/icons/icons/clouds.png"))
        self.label_3.setObjectName("label_3")
        self.label.raise_()
        self.lineEdit.raise_()
        self.pushButton.raise_()
        self.label_2.raise_()
        self.label_3.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "Search"))
        self.label_2.setText(_translate("Form", "WeatherApp"))
import loginResources
