# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plotWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Plot Window")
        MainWindow.resize(342, 221)
        MainWindow.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0.943, y1:0.0899545, x2:0, y2:1, stop:0 rgba(70, 76, 212, 255), stop:1 rgba(255, 255, 255, 116));")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(60, 40, 221, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setMinimumSize(QtCore.QSize(191, 31))
        self.comboBox.setStyleSheet("background-color:#ffffff;"
        "font-family: 'Roboto';"
"font-style: normal;"
"font-weight: 300;"
"font-size: 18px;"
"line-height: 21px;"
"letter-spacing: 0.04em;"

"color: rgba(0, 0, 0, 0.53);")
        self.comboBox.setObjectName("comboBox")
        self.plotButton = QtWidgets.QPushButton(self.centralwidget)
        self.plotButton.setGeometry(QtCore.QRect(110, 160, 121, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotButton.sizePolicy().hasHeightForWidth())
        self.plotButton.setSizePolicy(sizePolicy)
        self.plotButton.setMinimumSize(QtCore.QSize(91, 41))
        self.plotButton.setStyleSheet("background: #484DD5;\n"
"border-radius: 20px;\n"
"font-family: \'Roboto\';\n"
"font-style: normal;\n"
"font-weight: 200;\n"
"font-size: 18px;\n"
"line-height: 21px;\n"
"text-align: center;\n"
"letter-spacing: 0.04em;\n"
"color: #FFFFFF;\n"
"\n"
"")
        self.plotButton.setObjectName("plotButton")
        self.mornBox = QtWidgets.QCheckBox(self.centralwidget)
        self.mornBox.setGeometry(QtCore.QRect(20, 89, 89, 24))
        self.mornBox.setStyleSheet("font-family: \'Roboto\';\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 16px;\n"
"line-height: 21px;\n"
"letter-spacing: 0.04em;\n"
"background:none;\n"
"color:#ffffff")
        self.mornBox.setObjectName("mornBox")
        self.dayBox = QtWidgets.QCheckBox(self.centralwidget)
        self.dayBox.setGeometry(QtCore.QRect(115, 89, 98, 24))
        self.dayBox.setStyleSheet("font-family: \'Roboto\';\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 16px;\n"
"line-height: 21px;\n"
"letter-spacing: 0.04em;\n"
"background:none;\n"
"color:#ffffff")
        self.dayBox.setObjectName("dayBox")
        self.maxBox = QtWidgets.QCheckBox(self.centralwidget)
        self.maxBox.setGeometry(QtCore.QRect(219, 120, 102, 24))
        self.maxBox.setStyleSheet("font-family: \'Roboto\';\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 16px;\n"
"line-height: 21px;\n"
"letter-spacing: 0.04em;\n"
"background:none;\n"
"color:#ffffff")
        self.maxBox.setObjectName("maxBox")
        self.minBox = QtWidgets.QCheckBox(self.centralwidget)
        self.minBox.setGeometry(QtCore.QRect(115, 120, 98, 24))
        self.minBox.setStyleSheet("font-family: \'Roboto\';\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 16px;\n"
"line-height: 21px;\n"
"letter-spacing: 0.04em;\n"
"background:none;\n"
"color:#ffffff")
        self.minBox.setObjectName("minBox")
        self.eveBox = QtWidgets.QCheckBox(self.centralwidget)
        self.eveBox.setGeometry(QtCore.QRect(219, 89, 102, 24))
        self.eveBox.setStyleSheet("font-family: \'Roboto\';\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 16px;\n"
"line-height: 21px;\n"
"letter-spacing: 0.04em;\n"
"background:none;\n"
"color:#ffffff")
        self.eveBox.setTristate(False)
        self.eveBox.setObjectName("eveBox")
        self.nightBox = QtWidgets.QCheckBox(self.centralwidget)
        self.nightBox.setGeometry(QtCore.QRect(20, 120, 89, 24))
        self.nightBox.setStyleSheet("font-family: \'Roboto\';\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 16px;\n"
"line-height: 21px;\n"
"letter-spacing: 0.04em;\n"
"background:none;\n"
"color:#ffffff")
        self.nightBox.setObjectName("nightBox")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.plotButton.setText(_translate("MainWindow", "Plot"))
        self.mornBox.setText(_translate("MainWindow", "Morning"))
        self.dayBox.setText(_translate("MainWindow", "Day"))
        self.maxBox.setText(_translate("MainWindow", "Maximum"))
        self.minBox.setText(_translate("MainWindow", "Minimum"))
        self.eveBox.setText(_translate("MainWindow", "Evening"))
        self.nightBox.setText(_translate("MainWindow", "Night"))
