# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plotWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(342, 170)
        MainWindow.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0.943, y1:0.0899545, x2:0, y2:1, stop:0 rgba(70, 76, 212, 255), stop:1 rgba(255, 255, 255, 116));")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(60, 40, 221, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setMinimumSize(QtCore.QSize(191, 31))
        self.comboBox.setStyleSheet("background-color:#ffffff;"
        "font-family: 'Roboto';"
"font-style: normal;"
"font-weight: 300;"
"font-size: 18px;"
"line-height: 21px;"
"letter-spacing: 0.04em;"

"color: rgba(0, 0, 0, 0.53);")
        self.comboBox.setObjectName("comboBox")
        self.plotButton = QtWidgets.QPushButton(self.centralwidget)
        self.plotButton.setGeometry(QtCore.QRect(110, 102, 121, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plotButton.sizePolicy().hasHeightForWidth())
        self.plotButton.setSizePolicy(sizePolicy)
        self.plotButton.setMinimumSize(QtCore.QSize(91, 41))
        self.plotButton.setStyleSheet("background: #484DD5;\n"
"border-radius: 20px;\n"
"font-family: \'Roboto\';\n"
"font-style: normal;\n"
"font-weight: 200;\n"
"font-size: 18px;\n"
"line-height: 21px;\n"
"text-align: center;\n"
"letter-spacing: 0.04em;\n"
"color: #FFFFFF;\n"
"\n"
"")
        self.plotButton.setObjectName("plotButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.plotButton.setText(_translate("MainWindow", "Plot"))
